name = "DateNanoTimes.jl"
uuid = "91b9fbd0-876c-4b0b-babb-bf6877353220"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]
keywords = ["Julia", "date", "time", "nanosecond"]
description = "DateNanoTime is a nanosecond resolved DateTime type"
license = "MIT"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

